/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tech;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Well well well, how the turntables have turned.")
        return true;
    }
}
